[build.environment]
DART_SASS_VERSION = "1.97.3"
GO_VERSION = "1.26.0"
HUGO_VERSION = "0.157.0"
NODE_VERSION = "24.13.1"
TZ = "Asia/Shanghai"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """
